### ISSUE TITLE
Tracking box annotations corrupted at export

### ISSUE THREAD

**Issue by PAmerikanos** [openvinotoolkit/cvat#3300]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)
- [X] Ran it on FOUR separate machines (Win10, 2x Ubuntu20.04, MacOS 11)

### Expected Behaviour
When dumping an annotationset or exporting a dataset that contains tracking boxes, the resulting annotations contain bounding boxes that should move along with the identified moving features in the dataset.

### Current Behaviour
When dumping an annotationset or exporting a dataset that contains tracking boxes, the resulting annotations contain a significant amount of bounding boxes that do not move along with the identified moving features in the dataset. What makes it particularly strange is that not all bounding boxes display this wrong behaviour, but some do move correctly along with the tracked feature, as intended.
The export formats examined include YOLO, COCO, TFrecords and CVAT for images, which all present the exact same behaviour. This leads me to believe that something is wrong with the export process. 

### Possible Solution
No possible solution has been found.

### Steps to Reproduce (for bugs)

1. Create new project/new task/new job
2. Annotate a few moving features with the tracked bounding rectangle box (Instructions here: https://openvinotoolkit.github.io/cvat/docs/for-users/user-guide/basics/track-mode-basics/)
3. Optional: Save annotations
4. Export annotations with any of the above formats (YOLO, COCO, TFrecords and CVAT for images)
5. Remove all annotations in the same job
6. Upload annotations zip file previously exported
7. Examine a few of the moving/tracking bounding boxes. Some move along the moving features, some do not.

### Context
This does not allow us to export useful annotations for moving features, and has stopped our data processing pipeline.

### Your Environment

- Git hash commit (`git log -1`): `commit 241fb487abccb278803372e2b12148e030088b63 (HEAD -> develop, origin/develop, origin/HEAD)`
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.7
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Tried on Ubuntu 20.04, Windows 10, MacOS 11

Thank you for your time, any help would be more than welcome.
![git_help](https://user-images.githubusercontent.com/39599305/121020663-3fe05900-c7a9-11eb-9210-8baaacfc8989.jpeg)

**Comment by kirill-sizov** [comment]
Hi, @PAmerikanos.
I was unable to reproduce your problem.
I followed your steps, but my exported annotations are the same as the original annotations.
Could you please describe in more detail your actions in the annotation step (step 2)?
And how did you add images to the task?

**Comment by PAmerikanos** [comment]
Hi @kirill-sizov ,

Firstly, thank you for your time :)

The images were JPEGs extracted as sequential frames from a videofile, but they may as well be any kind of image. They were added to an empty task, uploaded from local disk to remote CVAT Docker instances.
The annotating process was as follows:
1. Transport to 1st frame where tracking begins
2. Draw new rectangle (Track) around object to be tracked
-- In our instances the objects move in a completely straight line --
3. Transport to last frame where object stops moving
4. Click Switch Outside Property to close tracking box
5. Repeat for next object of interest

What we found is that the problem described above arises when we **only use two keyframes**, one for the start and one for the end of tracking. If we use at least a third keyframe somewhere inbetween, either for adjustment or just as an extra closing marker, the annotations are exported correctly in all formats.

Therefore, perhaps this is a corner case where tracking is done with only two keyframes per tracking box?

Thanks again, if you need any clarification don't hesitate to let me know.

**Comment by kirill-sizov** [comment]
Hi, @PAmerikanos, we have fixed this bug. You can now upgrade to the current version of the develop branch and check your issue. Could you please leave feedback whether your problem is solved or not?

**Comment by PAmerikanos** [comment]
Hi @kirill-sizov,
Apologies for being a bit late, and thank you for your time.
I loaded the latest version of the develop branch and the issue seems to have been resolved.
I tested by exporting to CVAT video, CVAT images, YOLO and COCO. All seemed to work properly.

Thanks again
