### ISSUE TITLE
Problems with 3D annotation in milestone #6

### ISSUE THREAD

**Issue by nmanovic** [openvinotoolkit/cvat#3438]
- [ ] _Problem: Initial state of the loaded scene is useless_

![image](https://user-images.githubusercontent.com/40690625/126159244-c2692e8e-6691-470d-a9d6-e6515f122b7c.png)

When an user goes to a frame he/she should see the full scene. I will recommend to use "bird eye view" (top view) because it is easy to recognize the road, cars and other objects. Now users have to zoom out always (unnecessary action). The reference tool is initialized by a side view where all points are visible. It is also an acceptable solution.

- [ ] _Problem: black and white points without colors_

![image](https://user-images.githubusercontent.com/40690625/126160039-2b65f3c9-ee32-4bed-94a9-8e10881fe730.png)

It was already a long story. Let me come back to the decision to show black and white points. The reference tool assigns different colors to a point depends on the distance from the ego-vehicle. Let me understand reasons why CVAT doesn't do that as well.

- [ ] _Problem: Frame manipulation by mouse isn't activated by default in "select" mode_

When a 3D task is loaded, it doesn't allow users to manipulate with the loaded 3D frame using mouse. It isn't how the reference tool works and CVAT 2D works. It isn't convenient.
Furthermore, if I choose "move" mode and go to another frame, "select" mode is activated and I _can_ manipulate with the frame. Thus I can reproduce performance problems, which were reported previously.

AR: please fix performance problems, but don't break/disable expected features and functionality.

- [ ] _Problem: Projection of points on side and front views is excess_

![image](https://user-images.githubusercontent.com/40690625/126162053-3cfd17d9-f542-48b5-8e04-7d1a60baefbf.png)

Projection of points on "side" and "front" views is excess. Please look at the reference tool and compare the current implementation in CVAT and expected implementation in the reference tool. On the same PCD file, in CVAT it is mostly impossible to see boundaries of objects on "side" and "front" views. Looks like points which are far away of the 3D bounding box should not be displayed at all.

- [ ] _Problem: Shape selection works with a significant delay_

When I'm moving mouse under shapes, the selection works with a significant delay. I don't see the problem in the reference tool. Also, if I change "opacity" in the right side bar, UI is very unresponsive.

**Comment by bsekachev** [comment]
- [ ] Problem: Cuboid can not be drawn in some cases

Start drawing a cuboid using a standard way, double-click a perspective view. UI is broken, cuboid cannot be drawn anymore, event in a new drawing session. Need to reload the page.

**Comment by bsekachev** [comment]
We can close it now
